name: CI

on: [pull_request]

jobs:
  benchmark:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-go@v1
    - run: go get golang.org/x/tools/cmd/benchcmp
    - name: Check out base branch
      uses: actions/checkout@master
      with:
        ref: ${{ github.base_ref }}
    - name: Perform previous benchmark
      run: |
        cd $GITHUB_WORKSPACE
        go test -run=NONE -benchmem=true -bench=. ./... > old.txt
    - name: Check out head branch
      uses: actions/checkout@v1
      with:
        ref: ${{ github.head_ref }}
    - name: Perform current benchmark
      run: |
        cd $GITHUB_WORKSPACE
        go test -run=NONE -benchmem=true -bench=. ./... > new.txt
    - name: Compare benchmarks
      run: benchcmp old.text new.text
    - name: Print env
      run: printenv
    - name: Print POST event
      run: cat $GITHUB_EVENT_PATH
