name: CI

on: [pull_request]

jobs:
  benchmark:

    runs-on: ubuntu-latest
    
    steps:    
    - uses: actions/setup-go@v1
    - name: Perform previous benchmark
      uses: actions/checkout@v1
      with:
        ref: $GITHUB_BASE_REF
      run: |
        go test -run=NONE -benchmem=true -bench=. ./... > old.txt
    - name: Perform current benchmark
      uses: actions/checkout@v1
      with:
        ref: $GITHUB_HEAD_REF
      run: |
        go test -run=NONE -benchmem=true -bench=. ./... > old.txt
    - name: Compare benchmarks
      run: benchmp old.text new.text
    - name: Print env
      run: printenv
    - name: Print POST event
      run: cat $GITHUB_EVENT_PATH        
