name: CI

on: [pull_request]

jobs:
  benchmark:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-go@v1
    - name: Print env
      run: printenv
    - name: Print POST event
      run: cat $GITHUB_EVENT_PATH
    - name: Check out base branch
      uses: actions/checkout@master
      with:
        ref: ${{ github.base_ref }}
    - name: Perform previous benchmark
      run: |
        cd $GITHUB_WORKSPACE
        mkdir $HOME/benchmarks
        go test -run=NONE -benchmem=true -bench=. ./... > $HOME/benchmarks/old.txt
    - name: Check out head branch
      uses: actions/checkout@v1
      with:
        ref: ${{ github.head_ref }}
    - name: Perform current benchmark
      run: |
        cd $GITHUB_WORKSPACE
        go test -run=NONE -benchmem=true -bench=. ./... > $HOME/benchmarks/new.txt
    - name: Compare benchmarks
      uses: ./.github/actions/go-benchmark-action
      env:
        GO_BENCHMARK_DIR: $HOME/benchmarks
