name: CI

on: [pull_request]

jobs:
  benchmark:

    runs-on: ubuntu-latest

    steps:
    - name: Print env
      run: printenv
    - name: Print POST event
      run: cat $GITHUB_EVENT_PATH
    - name: Check out base branch
      uses: actions/checkout@master
    - name: Compare benchmarks
      uses: shipt/go-benchmark-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
